name: Build and deploy ASP.Net Core app to Azure Web App - ecommerce-backend-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore EcommerceApp/EcommerceApp.sln

      - name: Build with dotnet
        run: dotnet build EcommerceApp/EcommerceApp.sln --configuration Release --no-restore

      - name: Publish app
        run: dotnet publish EcommerceApp/EcommerceApp.sln -c Release -o ./publish

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C6B3AD28A5964534B96FDD409AEA211C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A021377B673B40D7BBD39AAD9A9D0BB5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FCCB26F488094A5E8D3C6BA205464B62 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ecommerce-backend-api'
          slot-name: 'Production'
          package: ./backend-app
